'use strict';

/**
 * The Step 17C-A ingest contract, enforced as code.
 *
 * Every rule here mirrors a rule in docs/17c-a-ingest-architecture.md (§3.2,
 * §3.3, §4.1–§4.4) and the database constraints in 0005 that migration 0011
 * will re-check on its own side. This module validates a batch and returns
 * named problems; it never fetches, never writes and never repairs a payload.
 * A malformed record is reported, never coerced:
 *
 *   1. the connector maps a source record onto this shape;
 *   2. this module refuses what the boundary would refuse;
 *   3. a later migration refuses the same things again, in the database,
 *      because a caller cannot be trusted with its own compliance.
 *
 * Nothing in 17C-B sends a batch anywhere. Validation exists so the shape is
 * proven before a database function has to enforce it.
 */

const crypto = require('node:crypto');

const BATCH_VERSION = 1;

/** The limits in 17C-A §4.4 (decision D7). */
const LIMITS = {
  recordsPerBatch: 500,
  rawBytes: 20480,
  mediaPerRecord: 30,
  externalProductIdMax: 200,
  titleMax: 500,
  descriptionMax: 8000,
  availabilityMax: 200,
  categoryMax: 300,
  merchantNameMax: 200,
  merchantRefMax: 200,
  sourceUrlMax: 1000,
  attributionMax: 200,
  connectorTextMax: 120,
  priceIntegerDigits: 12,
  priceDecimalPlaces: 2
};

const PATTERNS = {
  uuid: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  url: /^https?:\/\/\S+$/i,
  currency: /^[A-Z]{3}$/,
  country: /^[A-Z]{2}$/,
  price: new RegExp('^\\d{1,' + LIMITS.priceIntegerDigits + '}(\\.\\d{1,' + LIMITS.priceDecimalPlaces + '})?$'),
  noControl: /^[^\u0000-\u001f\u007f]+$/,
  iso8601: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2})$/
};

const ENVELOPE_KEYS = ['batch_version', 'source_id', 'job_id', 'connector', 'fetched_at', 'records'];
const CONNECTOR_KEYS = ['name', 'version', 'method'];
const CONNECTOR_METHODS = ['json-api', 'csv', 'xml', 'merchant-api'];
const RECORD_KEYS = ['external_product_id', 'source_url', 'title', 'description', 'price',
  'availability_text', 'category_text', 'merchant', 'media', 'raw'];
const PRICE_KEYS = ['amount', 'currency'];
const MERCHANT_KEYS = ['name', 'merchant_ref', 'website_url', 'country'];
const MEDIA_KEYS = ['url', 'media_type', 'sort_order', 'attribution', 'fallback_url'];
const MEDIA_TYPES = ['image', 'video', 'document'];

/**
 * Keys a connector may never set, each with the reason the boundary refuses it
 * (17C-A §3.3). They are refused by name so the failure is a sentence a person
 * can act on rather than a constraint violation to look up.
 */
const FORBIDDEN_RECORD_KEYS = new Map([
  ['pipeline_status', 'the pipeline records its own position; a caller cannot claim one'],
  ['validation_status', 'written by the validation stage'],
  ['validation_result', 'written by the validation stage'],
  ['normalization_status', 'written by the normalization stage'],
  ['normalization_result', 'written by the normalization stage'],
  ['normalized_name', 'normalization output'],
  ['normalized_brand', 'normalization output'],
  ['normalized_category_id', 'normalization output'],
  ['normalized_availability', 'normalization output'],
  ['model_number', 'normalization output'],
  ['gtin', 'normalization output'],
  ['deduplication_status', 'written by the deduplication stage'],
  ['deduplication_result', 'written by the deduplication stage'],
  ['dedup_match_class', 'written by the deduplication stage'],
  ['dedup_matched_deal_id', 'written by the deduplication stage'],
  ['review_status', 'an administrator decision'],
  ['review_note', 'an administrator decision'],
  ['reviewed_at', 'an administrator decision'],
  ['reviewed_by', 'an administrator decision'],
  ['published_deal_id', 'publication is not part of ingestion'],
  ['affiliate_url', 'never generated and never supplied by a source'],
  ['external_merchant_id', 'assigned by the ingest boundary from the merchant the record names'],
  ['id', 'generated by the database'],
  ['imported_at', 'generated by the database'],
  ['created_at', 'generated by the database'],
  ['updated_at', 'generated by the database'],
  ['job_id', 'belongs to the batch envelope'],
  ['source_id', 'belongs to the batch envelope'],
  ['error', 'processing state, not a caller-supplied message'],
  ['last_seen_at', 'written by the ingest boundary'],
  ['raw_hash', 'written by the ingest boundary']
]);

/* ---------------------------------------------------------------- helpers -- */

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isBlank(value) {
  return typeof value !== 'string' || value.trim() === '';
}

function trimmed(value) {
  return typeof value === 'string' ? value.trim() : '';
}

/**
 * A deterministic text form of a JSON value: object keys sorted, arrays in
 * order. The database computes its own hash from jsonb in 17C-C; this local
 * form exists so the dry run can tell "the same record again" from "the record
 * changed" without storing anything. It is never sent anywhere.
 */
function canonicalJson(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(canonicalJson).join(', ') + ']';
  const keys = Object.keys(value).sort();
  return '{' + keys.map((key) => JSON.stringify(key) + ': ' + canonicalJson(value[key])).join(', ') + '}';
}

function byteLength(text) {
  return Buffer.byteLength(text, 'utf8');
}

function hashRaw(raw) {
  return crypto.createHash('md5').update(canonicalJson(raw), 'utf8').digest('hex');
}

/** `<source_id>|<external_product_id>` — the identity 0011's unique index enforces. */
function identityKey(sourceId, externalProductId) {
  return String(sourceId) + '|' + String(externalProductId);
}

/* -------------------------------------------------------------- validators -- */

function checkUnknownKeys(object, allowed, field, errors) {
  for (const key of Object.keys(object)) {
    if (allowed.includes(key)) continue;
    const forbidden = FORBIDDEN_RECORD_KEYS.get(key);
    errors.push({
      field: field ? field + '.' + key : key,
      reason: forbidden ? 'refused: ' + forbidden : 'not part of the ingest contract'
    });
  }
}

function checkText(value, field, errors, options) {
  const opts = options || {};
  if (value === undefined || value === null) {
    if (opts.required) errors.push({ field: field, reason: 'is required' });
    return '';
  }
  if (typeof value !== 'string') {
    errors.push({ field: field, reason: 'must be a string' });
    return '';
  }
  const text = opts.trim === false ? value : value.trim();
  if (opts.required && text === '') errors.push({ field: field, reason: 'must not be blank' });
  if (opts.max && text.length > opts.max) {
    errors.push({ field: field, reason: 'must be at most ' + opts.max + ' characters (got ' + text.length + ')' });
  }
  if (opts.pattern && text !== '' && !opts.pattern.test(text)) {
    errors.push({ field: field, reason: opts.patternReason });
  }
  if (opts.noControl && text !== '' && !PATTERNS.noControl.test(text)) {
    errors.push({ field: field, reason: 'must not contain control characters' });
  }
  return text;
}

function checkUrl(value, field, errors, options) {
  const opts = options || {};
  return checkText(value, field, errors, {
    required: opts.required,
    max: opts.max,
    pattern: PATTERNS.url,
    patternReason: 'must be an http(s) address'
  });
}

function checkUuid(value, field, errors) {
  if (typeof value !== 'string' || !PATTERNS.uuid.test(value)) {
    errors.push({ field: field, reason: 'must be a uuid' });
  }
}

function validateConnector(connector, errors) {
  if (!isPlainObject(connector)) {
    errors.push({ field: 'connector', reason: 'must be a JSON object' });
    return;
  }
  checkUnknownKeys(connector, CONNECTOR_KEYS, 'connector', errors);
  checkText(connector.name, 'connector.name', errors, { required: true, max: LIMITS.connectorTextMax });
  checkText(connector.version, 'connector.version', errors, { required: true, max: LIMITS.connectorTextMax });
  if (!CONNECTOR_METHODS.includes(connector.method)) {
    errors.push({
      field: 'connector.method',
      reason: 'must be one of ' + CONNECTOR_METHODS.join(', ')
    });
  }
}

function validateEnvelope(batch) {
  const errors = [];
  if (!isPlainObject(batch)) {
    return { ok: false, errors: [{ field: 'batch', reason: 'the payload must be a JSON object' }] };
  }
  checkUnknownKeys(batch, ENVELOPE_KEYS, '', errors);
  if (batch.batch_version !== BATCH_VERSION) {
    errors.push({ field: 'batch_version', reason: 'must be ' + BATCH_VERSION });
  }
  checkUuid(batch.source_id, 'source_id', errors);
  checkUuid(batch.job_id, 'job_id', errors);
  validateConnector(batch.connector, errors);
  if (typeof batch.fetched_at !== 'string' || !PATTERNS.iso8601.test(batch.fetched_at)) {
    errors.push({ field: 'fetched_at', reason: 'must be an ISO 8601 timestamp with an offset, for example 2026-09-26T10:00:00Z' });
  }
  if (!Array.isArray(batch.records)) {
    errors.push({ field: 'records', reason: 'must be an array' });
  } else if (batch.records.length === 0) {
    errors.push({ field: 'records', reason: 'must contain at least one record' });
  } else if (batch.records.length > LIMITS.recordsPerBatch) {
    errors.push({ field: 'records', reason: 'must not exceed ' + LIMITS.recordsPerBatch + ' records in one call' });
  }
  return { ok: errors.length === 0, errors: errors };
}

function validatePrice(price, errors) {
  if (price === undefined || price === null) return;
  if (!isPlainObject(price)) {
    errors.push({ field: 'price', reason: 'must be an object carrying amount and currency, or null' });
    return;
  }
  checkUnknownKeys(price, PRICE_KEYS, 'price', errors);
  const amount = checkText(price.amount, 'price.amount', errors, {
    required: true,
    max: 20,
    pattern: PATTERNS.price,
    patternReason: 'must be a decimal string with at most ' + LIMITS.priceDecimalPlaces + ' decimal places (a symbol, separator or currency conversion is not accepted)'
  });
  checkText(price.currency, 'price.currency', errors, {
    required: true,
    max: 3,
    pattern: PATTERNS.currency,
    patternReason: 'must be a three-letter ISO 4217 code in upper case, such as KES, USD or EUR'
  });
  if (price.amount === undefined || price.amount === null) {
    errors.push({ field: 'price', reason: 'a price with no amount must be null, not an empty object' });
  }
}

function validateMerchant(merchant, errors) {
  if (!isPlainObject(merchant)) {
    errors.push({ field: 'merchant', reason: 'must be a JSON object naming the merchant the record came from' });
    return;
  }
  checkUnknownKeys(merchant, MERCHANT_KEYS, 'merchant', errors);
  checkText(merchant.name, 'merchant.name', errors, { required: true, max: LIMITS.merchantNameMax });
  checkText(merchant.merchant_ref, 'merchant.merchant_ref', errors, { max: LIMITS.merchantRefMax });
  checkUrl(merchant.website_url, 'merchant.website_url', errors, { max: LIMITS.sourceUrlMax });
  checkText(merchant.country, 'merchant.country', errors, {
    max: 2,
    pattern: PATTERNS.country,
    patternReason: 'must be a two-letter ISO 3166-1 code in upper case, such as KE, GB or DE'
  });
}

function validateMedia(media, errors) {
  if (media === undefined || media === null) return;
  if (!Array.isArray(media)) {
    errors.push({ field: 'media', reason: 'must be an array of references' });
    return;
  }
  if (media.length > LIMITS.mediaPerRecord) {
    errors.push({ field: 'media', reason: 'must not exceed ' + LIMITS.mediaPerRecord + ' references' });
  }
  const orders = new Set();
  media.forEach((entry, index) => {
    const field = 'media[' + index + ']';
    if (!isPlainObject(entry)) {
      errors.push({ field: field, reason: 'must be a JSON object' });
      return;
    }
    checkUnknownKeys(entry, MEDIA_KEYS, field, errors);
    checkUrl(entry.url, field + '.url', errors, { required: true, max: LIMITS.sourceUrlMax });
    checkUrl(entry.fallback_url, field + '.fallback_url', errors, { max: LIMITS.sourceUrlMax });
    if (entry.media_type !== undefined && !MEDIA_TYPES.includes(entry.media_type)) {
      errors.push({ field: field + '.media_type', reason: 'must be one of ' + MEDIA_TYPES.join(', ') });
    }
    if (entry.attribution !== undefined) {
      checkText(entry.attribution, field + '.attribution', errors, { max: LIMITS.attributionMax });
    }
    if (entry.sort_order !== undefined) {
      if (!Number.isInteger(entry.sort_order) || entry.sort_order < 0) {
        errors.push({ field: field + '.sort_order', reason: 'must be an integer of at least 0' });
      } else if (orders.has(entry.sort_order)) {
        errors.push({ field: field + '.sort_order', reason: 'must be unique within a record (got ' + entry.sort_order + ' twice)' });
      } else {
        orders.add(entry.sort_order);
      }
    }
  });
}

/**
 * Validates one record and returns `{index, external_product_id, ok, errors}`.
 * Every problem carries the field and a sentence, because that is what a person
 * reading a run report needs and what 0011 will return.
 */
function validateRecord(record, index) {
  const errors = [];
  const externalProductId = isPlainObject(record) ? trimmed(record.external_product_id) : '';
  if (!isPlainObject(record)) {
    return {
      index: index,
      external_product_id: '',
      ok: false,
      errors: [{ field: 'record', reason: 'must be a JSON object' }]
    };
  }
  checkUnknownKeys(record, RECORD_KEYS, '', errors);
  checkText(record.external_product_id, 'external_product_id', errors, {
    required: true,
    max: LIMITS.externalProductIdMax,
    noControl: true
  });
  checkUrl(record.source_url, 'source_url', errors, { required: true, max: LIMITS.sourceUrlMax });
  checkText(record.title, 'title', errors, { required: true, max: LIMITS.titleMax });
  checkText(record.description, 'description', errors, { max: LIMITS.descriptionMax });
  checkText(record.availability_text, 'availability_text', errors, { max: LIMITS.availabilityMax });
  checkText(record.category_text, 'category_text', errors, { max: LIMITS.categoryMax });
  validatePrice(record.price, errors);
  validateMerchant(record.merchant, errors);
  validateMedia(record.media, errors);
  if (!isPlainObject(record.raw)) {
    errors.push({ field: 'raw', reason: 'must be the source record as a JSON object, unchanged' });
  } else {
    const size = byteLength(canonicalJson(record.raw));
    if (size > LIMITS.rawBytes) {
      errors.push({ field: 'raw', reason: 'must be at most ' + LIMITS.rawBytes + ' bytes of JSON (got ' + size + ')' });
    }
  }
  return { index: index, external_product_id: externalProductId, ok: errors.length === 0, errors: errors };
}

function validateBatch(batch) {
  const envelope = validateEnvelope(batch);
  const records = Array.isArray(batch && batch.records)
    ? batch.records.map((record, index) => validateRecord(record, index))
    : [];
  return { ok: envelope.ok && records.every((r) => r.ok), envelope: envelope, records: records };
}

/** Counts for a report: what a run saw, and what was refused. */
function summarise(records) {
  const summary = { records: records.length, valid: 0, rejected: 0 };
  for (const record of records) {
    if (record.ok) summary.valid += 1;
    else summary.rejected += 1;
  }
  return summary;
}

module.exports = {
  BATCH_VERSION: BATCH_VERSION,
  LIMITS: LIMITS,
  PATTERNS: PATTERNS,
  ENVELOPE_KEYS: ENVELOPE_KEYS,
  CONNECTOR_KEYS: CONNECTOR_KEYS,
  CONNECTOR_METHODS: CONNECTOR_METHODS,
  RECORD_KEYS: RECORD_KEYS,
  PRICE_KEYS: PRICE_KEYS,
  MERCHANT_KEYS: MERCHANT_KEYS,
  MEDIA_KEYS: MEDIA_KEYS,
  MEDIA_TYPES: MEDIA_TYPES,
  FORBIDDEN_RECORD_KEYS: FORBIDDEN_RECORD_KEYS,
  isPlainObject: isPlainObject,
  isBlank: isBlank,
  canonicalJson: canonicalJson,
  byteLength: byteLength,
  hashRaw: hashRaw,
  identityKey: identityKey,
  validateEnvelope: validateEnvelope,
  validateRecord: validateRecord,
  validateBatch: validateBatch,
  summarise: summarise
};
